---
## tasks main.yml for role: impacket
## This role downloads and installs impacket
##########################
## Install Impacket

## Note: Download of the source is controlled in the threatbox.yml file. 
##       It's best to enable all downloads in that file. 
##       This help to maintain software package tracking.

- name: Set impacket path variable
  set_fact:
      tool_path: "{{ tools_root }}/{{ item.value.category }}/{{ item.key }}/"
  loop: "{{ lookup('dict', git_repos) }}"
  when: "'impacket' in item.key" 


### Check if tool_path exists
- name: check for tool_path ({{ tool_path }})
  stat:
    path: "{{ tool_path }}"
  register: tp


- name: fail if tool_path ({{ tool_path }}) does not exist
  fail: msg="The directory does not exist"
  when: not tp.stat.exists  


- name: install impacket
  raw: cd {{ tool_path }} && pip install .

