---
## tasks main.yml for role: crackmapexec

##########################
## CrackMapExec

- name: Set CrackMapExec path variable
  set_fact:
      tool_path: "{{ tools_root }}/{{ item.value.category }}/{{ item.key }}/"
  loop: "{{ lookup('dict', git_repos) }}"
  when: "'crackmapexec' in item.key" 


### Check if tool_path exists
- name: check for tool_path ({{ tool_path }})
  stat:
    path: "{{ tool_path }}"
  register: tp


- name: fail if tool_path ({{ tool_path }}) does not exist
  fail: msg="The directory does not exist"
  when: not tp.stat.exists  


- name: Install CrackMapExec - clean current pipenv
  shell: "pipenv --rm"
  args:
    chdir: "{{ tool_path }}"
  ignore_errors: yes


- name: Install CrackMapExec - set pipenv to python2.7
  shell: "pipenv --python 2.7"
  args:
    chdir: "{{ tool_path }}"


- name: Install CrackMapExec - Remove Pipfile files (requirements.txt is the source of truth here)
  file:
    path: "{{ item }}"
    state: absent
  loop:
      - "{{ tool_path }}/Pipfile"
      - "{{ tool_path }}/Pipfile.lock"


- name: Install CrackMapExec - pipenv install
  shell: "pipenv install"
  args:
    chdir: "{{ tool_path }}"
  async: 900
  poll: 30


- name: Install CrackMapExec - python setup.py
  shell: "pipenv run python setup.py install"
  args:
    chdir: "{{ tool_path }}"
  async: 900
  poll: 30
